# EVALUACION EXHAUSTIVA

In [187]:


import numpy as np
import wolframalpha
client = wolframalpha.Client("K56TY6-XQUK252299")
from ipywidgets import Layout, Button, Box, VBox

# Items flex proportionally to the weight and the left over space around the text
items_0 = [widgets.FloatText(value=i+1) for i in range(0,4)]
items_1 = [widgets.FloatText(value=i+1) for i in range(4,8)]
items_2 = [widgets.FloatText(value=i+1) for i in range(8,12)]
items_3 = [widgets.FloatText(value=i+1) for i in range(12,16)]
box_layout = Layout(display='flex',
                    flex_flow='row',
                    align_items='stretch',
                    width='100%')
box_0 = Box(children=items_0, layout=box_layout)
box_1 = Box(children=items_1, layout=box_layout)
box_2 = Box(children=items_2, layout=box_layout)
box_3 = Box(children=items_3, layout=box_layout)
VBox([box_0,box_1,box_2,box_3])


In [169]:
print('Politica a evaluar separada por comas')
poli=widgets.Text(
    placeholder='1,1,3,1')
poli

Politica a evaluar separada por comas


Text(value='', placeholder='1,2,3,1')

In [305]:
arr=[[.48,.30,.22,0],[.59,.27,.14,0],[.43,.26,.31,0],[0,0,0,0]]
#arr=[[items_0[i].value for i in range(0,4)]
#     ,[items_1[i].value for i in range(0,4)]
#     ,[items_2[i].value for i in range(0,4)]
#     ,[items_3[i].value for i in range(0,4)]]
original=np.array(arr)
original

array([[0.48, 0.3 , 0.22, 0.  ],
       [0.59, 0.27, 0.14, 0.  ],
       [0.43, 0.26, 0.31, 0.  ],
       [0.  , 0.  , 0.  , 0.  ]])

In [306]:
np.sum(original,axis=1)

array([1., 1., 1., 0.])

In [307]:

pol=[2,2,3,3]
for i in range(0,4):
    if pol[i]==1:
        continue
    elif pol[i]==2:
        for j in range(0,4):
            if j==1:
                original[i][j]=1
            else:
                original[i][j]=0
    elif pol[i]==3:
        for j in range(0,4):
            if j==0:
                original[i][j]=1
            else:
                original[i][j]=0
            
original

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [308]:
trans=np.transpose(original)
trans

array([[0., 0., 1., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [309]:
for i in range(0,4):
    trans[i][i]=trans[i][i]-1
trans

array([[-1.,  0.,  1.,  1.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0., -1.]])

In [310]:
for i in range(0,4):
    print("{} {} {} {} 0".format(trans[i][0],trans[i][1],trans[i][2],trans[i][3]))
print("1 1 1 1 1")

-1.0 0.0 1.0 1.0 0
1.0 0.0 0.0 0.0 0
0.0 0.0 -1.0 0.0 0
0.0 0.0 0.0 -1.0 0
1 1 1 1 1


In [311]:
costo=np.array([[7700,14500,0],[11700,18500,0],[16700,23500,26400],[0,0,26400]])
pi=[2950/6563,2600/6563,1013/6563,0]
costo=np.transpose(costo)
costo

array([[ 7700, 11700, 16700,     0],
       [14500, 18500, 23500,     0],
       [    0,     0, 26400, 26400]])

In [294]:
x_1=0
x_2=1
x_3=0
x_4=0
pi=np.array([x_1,x_2,x_3,x_4])
pi=np.around(pi, decimals=2)

pi

array([0, 1, 0, 0])

In [295]:
total=np.zeros((4,))
cont=0
for i in pol:
    total[cont]=costo[i-1][cont]
    cont+=1
total

array([14500., 18500., 16700., 26400.])

In [296]:
res=np.sum(np.multiply(total,pi),axis=0)
res

18500.0

In [297]:
print("Politica a evaluar", pol)
print("\n")
for i in range(0,4):
    print("{}a+ {}b+ {}c+ {}d= 0".format(trans[i][0],trans[i][1],trans[i][2],trans[i][3]))
print("a+b+c+d=1")

print("\n Vector PI ",pi)

print("\n {}*{} + {}*{} + {}*{} + {}*{}={}".format(pi[0],total[0],pi[1],total[1],pi[2],total[2],pi[3],total[3],res))

print("\n EL resultado es ",res)

Politica a evaluar [2, 2, 1, 3]


-1.0a+ 0.0b+ 0.43c+ 1.0d= 0
1.0a+ 0.0b+ 0.26c+ 0.0d= 0
0.0a+ 0.0b+ -0.69c+ 0.0d= 0
0.0a+ 0.0b+ 0.0c+ -1.0d= 0
a+b+c+d=1

 Vector PI  [0 1 0 0]

 0*14500.0 + 1*18500.0 + 0*16700.0 + 0*26400.0=18500.0

 EL resultado es  18500.0
